### ISSUE TITLE
Add support to be able to include as an AMD module

### ISSUE THREAD

**Issue by petulla** [bradoyler/googledoc-to-json#4]
Brad, is this a feature that could be added? I'd use it for upcoming projects if so.

Happy to try to dev it  if it is.

**Comment by petulla** [comment]
Awesome, looks like it was ready to go, will test.

**Comment by bradoyler** [comment]
yea, this should do it: https://github.com/bradoyler/googledoc-to-json#api
Re-open if u have any issues.
